### ISSUE TITLE
Docker Desktop - Internal Error 500

### ISSUE THREAD

**Issue by Majibear** [jkirkcaldy/plex-utills#100]
So typically while using Docker Desktop on Windows, you can reach other containers and the host applications by the DNS resolver 'host.docker.internal'. I use this for all my apps across Docker Desktop without issue.

I seem to be having a problem retaining this with plex-utils. I receive a 500 Internal Error as soon as I save the information. Yet the tool still works fine... at least up until I restart the container - and then I receive an nginx bad gateway error, and the app is dead until I delete the database and recreate the container all over again. If I save any other type of address the container can be restarted.

Any ideas why this is happening?

**Comment by charliik** [comment]
I've got similar issue.

**Comment by 338lm** [comment]
`2022-11-23T16:56:17.384288474Z | stdout | IndexError: list index out of range
-- | -- | --
2022-11-23T16:56:17.384261301Z | stdout | plexpath = '/'+filepath.split('/')[1]
2022-11-23T16:56:17.384231359Z | stdout | File "/app/app/__init__.py", line 141, in update_scheduler
2022-11-23T16:56:17.384206815Z | stdout | update_scheduler()
2022-11-23T16:56:17.384175441Z | stdout | File "/app/app/routes.py", line 152, in config
2022-11-23T16:56:17.384140085Z | stdout | return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2022-11-23T16:56:17.384110226Z | stdout | File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
2022-11-23T16:56:17.384085190Z | stdout | rv = self.dispatch_request()
2022-11-23T16:56:17.384054701Z | stdout | File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
2022-11-23T16:56:17.384027403Z | stdout | rv = self.handle_user_exception(e)
2022-11-23T16:56:17.383996085Z | stdout | File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
2022-11-23T16:56:17.383965986Z | stdout | response = self.full_dispatch_request()
2022-11-23T16:56:17.383925388Z | stdout | File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
2022-11-23T16:56:17.383873617Z | stdout | Traceback (most recent call last):
2022-11-23T16:56:17.383383505Z | stdout | [2022-11-23 11:56:17,381] ERROR in app: Exception on /config [POST]
2022-11-23T16:56:10.240694854Z | stdout | 2022-11-23 11:56:10,239 - SYS - 4K/HDR Posters schedule created for 06:00
2022-11-23T16:56:10.240486151Z | stdout | 2022-11-23 11:56:10,239 - SYS - 4K/HDR Posters schedule created for 06:00
2022-11-23T16:56:10.240233583Z | stdout | return self.timezone.localize(datetime(**values))
2022-11-23T16:56:10.240130713Z | stdout | /usr/local/lib/python3.9/site-packages/apscheduler/triggers/cron/__init__.py:159: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
2022-11-23T16:56:10.240083933Z | stdout | return self.timezone.normalize(dateval + difference), fieldnum
2022-11-23T16:56:10.239994333Z | stdout | /usr/local/lib/python3.9/site-packages/apscheduler/triggers/cron/__init__.py:146: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
2022-11-23T16:56:10.239590460Z | stdout | if obj.zone == 'local':
2022-11-23T16:56:10.239033312Z | stdout | /usr/local/lib/python3.9/site-packages/apscheduler/util.py:95: PytzUsageWarning: The zone attribute is specific to pytz's interface; please migrate to a new time zone provider. For more details on how to do so, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
`

**Comment by jkirkcaldy** [comment]
Should be solved on latest update.

**Comment by Silversurfer79** [comment]
Thanks for the good work, 

Its still not working. Synology NAS running Docker and Potainer in my case. Tyring to setup inside the app, get the error below.

[2023-04-24 23:36:22,983] ERROR in app: Exception on /config [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/app/config.py", line 51, in config
    update_scheduler(app)
  File "/app/app/schedule.py", line 24, in update_scheduler
    plex = PlexServer(config[0].plexurl, config[0].token)
  File "/usr/local/lib/python3.9/site-packages/plexapi/server.py", line 115, in __init__
    data = self.query(self.key, timeout=self._timeout)
  File "/usr/local/lib/python3.9/site-packages/plexapi/server.py", line 751, in query
    raise Unauthorized(message)
plexapi.exceptions.Unauthorized: (401) unauthorized; https://IP:plexstuff.plex.direct:32400/ <html><head><script>window.location = window.location.href.match(/(^.+\/)[^\/]*$/)[1] + 'web/index.html';</script><title>Unauthorized</title></head><body><h1>401 Unauthorized</h1></body></html>

My compase file
---
version: "3.7"
services:
  Radarr:
    image: jkirkcaldy/plex-utills:latest
    container_name: Plex-Utills
    environment:
      - PUID=****
      - PGID=******
      - TZ=Europe/London
    volumes:
      - /volume1/docker/plex-utills:/config
      - /volume1/docker/plex-utills/logs:/logs
      - /volume1/Media/Videos/Movies:/films
    ports:
      - 7979:80
    restart: always

> Should be solved on latest update.

**Comment by Silversurfer79** [comment]
I also noticed that It asks me to migrate, never having installed nor used this container before today, logs below.

[2023-04-25 09:11:56,250] - [Application] - [DEBUG] - Running setup Helper
[2023-04-25 09:11:56,266] - [Application] - [INFO] - creating backup directory now
/usr/local/lib/python3.9/site-packages/apscheduler/util.py:428: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
[2023-04-25 09:11:56,269] - [Application] - [DEBUG] - Running setup Helper
[2023-04-25 09:11:56,269] - [Application] - [DEBUG] - Running setup Helper
[2023-04-25 09:11:56,270] - [Application] - [DEBUG] - Running setup Helper
[2023-04-25 09:11:56,273] - [Application] - [DEBUG] - Running setup Helper
[2023-04-25 09:11:56,275] - [Application] - [DEBUG] - Running setup Helper
/usr/local/lib/python3.9/site-packages/apscheduler/util.py:428: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
/usr/local/lib/python3.9/site-packages/apscheduler/util.py:428: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
[2023-04-25 09:11:56,291] - [Application] - [INFO] - creating backup directory now
[2023-04-25 09:11:56,294] - [Application] - [INFO] - creating backup directory now
[2023-04-25 09:11:56,299] - [Application] - [INFO] - creating backup directory now
[2023-04-25 09:11:56,301] - [Application] - [DEBUG] - Running setup Helper
[2023-04-25 09:11:56,305] - [Application] - [DEBUG] - Running setup Helper
[2023-04-25 09:11:56,310] - [Application] - [INFO] - creating backup directory now
[2023-04-25 09:11:56,311] - [Application] - [INFO] - creating backup directory now
[2023-04-25 09:11:56,311] - [Application] - [DEBUG] - Running setup Helper
[2023-04-25 09:11:56,315] - [Application] - [INFO] - creating backup directory now
[2023-04-25 09:11:56,320] - [Application] - [INFO] - creating backup directory now
[2023-04-25 09:11:56,322] - [Application] - [INFO] - creating backup directory now

![Screen_Capture_-_25_Apr__9_17_am](https://user-images.githubusercontent.com/58236890/234203054-d0984eec-e5d3-4a3e-b523-0adfc174fa9e.png)

**Comment by Silversurfer79** [comment]
Please open

**Comment by keteflips** [comment]
Same bug here in TrueNAS

**Comment by Silversurfer79** [comment]
So this was a miss configuration on my side, url was incorrect for plex and nas didnt have the firewall port allowed. Once all of that was sorted I, went over to Config -> Server Config and then added my Plex URL and Token and it worked.
